# k8s/base/frontend-blue-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  labels:
    app: frontend
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      color: blue
  template:
    metadata:
      labels:
        app: frontend
        color: blue
    spec:
      containers:
      - name: frontend
        image: REPLACE_FRONTEND_IMAGE
        ports:
        - containerPort: 3000
        env:
        - name: ACTIVE_COLOR
          value: "blue"
