apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: blue            # initial color for blue/green
  template:
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
      - name: frontend
        image: REPLACE_FRONTEND_IMAGE   # will be patched by CI
        ports:
        - containerPort: 3000
