apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    version: blue       # points at the “blue” pods initially
  ports:
  - port: 80
    targetPort: 3000
