apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-blue
  labels:
    app: inventory
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
      color: blue
  template:
    metadata:
      labels:
        app: inventory
        color: blue
    spec:
      containers:
      - name: inventory
        image: REPLACE_INVENTORY_IMAGE
        ports:
        - containerPort: 3000
