apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
      version: blue     # initial version
  template:
    metadata:
      labels:
        app: inventory
        version: blue
    spec:
      containers:
      - name: inventory
        image: REPLACE_INVENTORY_IMAGE   # to be patched by overlays or CI
        ports:
        - containerPort: 3000
