apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-green
  labels:
    app: inventory
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
      color: green
  template:
    metadata:
      labels:
        app: inventory
        color: green
    spec:
      containers:
      - name: inventory
        image: REPLACE_INVENTORY_IMAGE
        ports:
        - containerPort: 3000
