resources:
  - login-blue-deploy.yaml
  - login-green-deploy.yaml
  - login-svc.yaml
  - order-blue-deploy.yaml
  - order-green-deploy.yaml
  - order-svc.yaml
  - inventory-green-deploy.yaml
  - inventory-blue-deploy.yaml
  - inventory-svc.yaml
  - frontend-blue-deploy.yaml
  - frontend-green-deploy.yaml
  - frontend-svc.yaml           
