# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Deployments (blue + green for each service)
  - login-blue-deploy.yaml
  - login-green-deploy.yaml
  - order-blue-deploy.yaml
  - order-green-deploy.yaml
  - inventory-blue-deploy.yaml
  - inventory-green-deploy.yaml
  - frontend-blue-deploy.yaml
  - frontend-green-deploy.yaml

  # Services
  - login-svc.yaml
  - order-svc.yaml
  - inventory-svc.yaml
  - frontend-svc.yaml
