apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-blue
  labels:
    app: login
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
      color: blue
  template:
    metadata:
      labels:
        app: login
        color: blue
    spec:
      containers:
      - name: login
        image: REPLACE_LOGIN_IMAGE
        ports:
        - containerPort: 3000
