apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  type: LoadBalancer
  selector:
    app: login
    version: blue        # traffic goes to “blue” initially
  ports:
  - port: 80
    targetPort: 3000
