apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
      version: blue     # initial version
  template:
    metadata:
      labels:
        app: order
        version: blue
    spec:
      containers:
      - name: order
        image: REPLACE_ORDER_IMAGE   # to be patched by overlays or CI
        ports:
        - containerPort: 3000
