apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-green
  labels:
    app: order
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
      color: green
  template:
    metadata:
      labels:
        app: order
        color: green
    spec:
      containers:
      - name: order
        image: REPLACE_ORDER_IMAGE
        ports:
        - containerPort: 3000
